package com.sample.ecofriendly.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Document(collection = "payments")
public class Payment {
    @Id
    private String id;
    private String userId;
    private String productId;
    private double amount;
    private String status;
    private LocalDateTime paymentDate;
    private String stripePaymentIntentId;
    private String paymentMethod; // Added paymentMethod field
    private String transactionId;

    // Constructors, getters, and setters can be generated by Lombok
}
